###

GET http://localhost:8081/menu/all HTTP/1.1
Content-Type: application/json

###


POST http://localhost:8081/menu/add HTTP/1.1
Content-Type: application/json

{
    "title": "Browse Categories",
    "position": 1,
    "children": [
        {
            "title": "Category1",
            "position": 1
        },
        {
            "title": "Category2",
            "position": 2
        }
    ]
}

###